package com.carpool.entity;

public enum NotificationType {
    NEW_BOOKING_REQUEST,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    PASSENGER_CANCELLATION,
    OWNER_RIDE_CANCELLATION,
    RIDE_COMPLETION,
    RIDE_POSTED,
    RATING_AVAILABLE,
    BOOKING_PENDING,
    RATING_RECEIVED,
    RIDE_CREATED,
    SUBSCRIPTION_PENDING,
    SUBSCRIPTION_PAYMENT_SUCCESS,
    SUBSCRIPTION_PAYMENT_FAILURE,
    KYC_VERIFICATION_RESULT
    ,
    TICKET_RAISED,
    TICKET_RESOLVED
}
